import Head from 'next/head'
import Image from 'next/image'

import Header from './components/Header'
import Nav from './components/Nav'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Nav/>
      <Header/>


    </div>
  )
}
